apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ingress-2048
  namespace: 2048-namespace
  labels:
    name: haproxy-ingress-2048
spec:
  # This line specifically targets the HAProxy Ingress Controller
  ingressClassName: haproxy
  rules:
  - host: "2048-haproxy.localtest.me"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-2048 # Name of your 2048 service
            port:
              number: 8084 # Port your 2048 service is listening on

status:
  loadBalancer:
    ingress:
    - hostname: localhost